# Generated by Django 5.2.10 on 2026-01-29 06:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('DEFAULT', 'Выберите управление'), ('ONE', 'Первое управление'), ('TWO', 'Второе управление'), ('THREE', 'Третье управление'), ('FOR', 'Четвертое управление')], default=users.enums.Departments['ONE'], max_length=25, verbose_name='Управление')),
            ],
            options={
                'verbose_name': 'Управление',
                'verbose_name_plural': 'Управления',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('USER', 'Пользователь'), ('EDITOR', 'Редактор'), ('ADMIN', 'Администратор')], default='USER', max_length=32, verbose_name='Роль')),
                ('rank', models.CharField(choices=[('ENLISTED', 'Служащий'), ('PRIVATE', 'Рядовой'), ('LANCE_CORPORAL', 'Ефрейтор'), ('JUNIOR_SERGEANT', 'Младший сержант'), ('SERGEANT', 'Сержант'), ('SEN_SERGEANT', 'Старший сержант'), ('SERGEANT_THIRD_CLASS', 'Сержант 3 класса'), ('SERGEANT_SECOND_CLASS', 'Сержант 2 класса'), ('SERGEANT_FIRST_CLASS', 'Сержант 1 класса'), ('STAFF_SERGEANT', 'Штаб-сержант'), ('MASTER_SERGEANT', 'Мастер-сержант'), ('LIEUTENANT', 'Лейтенант'), ('SENIOR_LIEUTENANT', 'Старший лейтенант'), ('CAPTAIN', 'Капитан'), ('MAJOR', 'Майор'), ('LIEUTENANT_COLONEL', 'Подполковник'), ('COLONEL', 'Полковник'), ('MAJOR_GENERAL', 'Генерал-майор'), ('LIEUTENANT_GENERAL', 'Генерал-лейтенант'), ('COLONEL_GENERAL', 'Генерал-полковник')], default='ENLISTED', max_length=64, verbose_name='Воинское звание')),
                ('middle_name', models.CharField(blank=True, max_length=128, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('work_phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате:\n             '24901 / +71112223344 / 81112223344'", regex='^\\+?\\d{5,15}$')], verbose_name='Рабочий телефон')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, default='ONE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.department', verbose_name='Управление')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
