# Generated by Django 5.2.10 on 2026-01-29 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_department_alter_user_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(choices=[('DEFAULT', 'Выберите управление'), ('ONE', 'Первое управление'), ('TWO', 'Второе управление'), ('THREE', 'Третье управление'), ('FOR', 'Четвертое управление')], default='ONE', max_length=25, verbose_name='Управление'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, default='ONE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.department', verbose_name='Управление'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('ENLISTED', 'Служащий'), ('PRIVATE', 'Рядовой'), ('LANCE_CORPORAL', 'Ефрейтор'), ('JUNIOR_SERGEANT', 'Младший сержант'), ('SERGEANT', 'Сержант'), ('SEN_SERGEANT', 'Старший сержант'), ('SERGEANT_THIRD_CLASS', 'Сержант 3 класса'), ('SERGEANT_SECOND_CLASS', 'Сержант 2 класса'), ('SERGEANT_FIRST_CLASS', 'Сержант 1 класса'), ('STAFF_SERGEANT', 'Штаб-сержант'), ('MASTER_SERGEANT', 'Мастер-сержант'), ('LIEUTENANT', 'Лейтенант'), ('SENIOR_LIEUTENANT', 'Старший лейтенант'), ('CAPTAIN', 'Капитан'), ('MAJOR', 'Майор'), ('LIEUTENANT_COLONEL', 'Подполковник'), ('COLONEL', 'Полковник'), ('MAJOR_GENERAL', 'Генерал-майор'), ('LIEUTENANT_GENERAL', 'Генерал-лейтенант'), ('COLONEL_GENERAL', 'Генерал-полковник')], default='ENLISTED', max_length=64, verbose_name='Воинское звание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Пользователь'), ('EDITOR', 'Редактор'), ('ADMIN', 'Администратор')], default='USER', max_length=32, verbose_name='Роль'),
        ),
    ]
