# Generated by Django 5.2.10 on 2026-01-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Управление'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('title',), name='uniq_department_title', violation_error_message='Такое управление уже есть в системе.'),
        ),
    ]
