# Generated by Django 5.2.10 on 2026-02-19 12:11

import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Подзадача (документы)',
                'verbose_name_plural': 'Подзадачи (документы)',
            },
        ),
        migrations.CreateModel(
            name='DocumentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closes_task_fully', models.BooleanField(default=False, verbose_name='Задача закрыта')),
            ],
            options={
                'verbose_name': 'Задача (документы)',
                'verbose_name_plural': 'Задачи (документы)',
            },
        ),
        migrations.CreateModel(
            name='ExternalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('year', models.SmallIntegerField(default=2026, verbose_name='Год')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата внесения ведомства в базу')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Ведомство',
                'verbose_name_plural': 'Ведомства',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название источника')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата фиксации источника')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('year', models.SmallIntegerField(default=2026, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Подзадача')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Подзадача закрыта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Задача')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Задача закрыта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('year', models.SmallIntegerField(default=2026, verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.CharField(max_length=50, verbose_name='Кодировка')),
                ('title', django_countries.fields.CountryField(max_length=2, verbose_name='Название страны')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания страны')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('year', models.PositiveSmallIntegerField(default=2026, verbose_name='Год создания')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'constraints': [models.UniqueConstraint(fields=('title', 'encoding', 'year'), name='unique_country_encoding_year')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Наименование справки')),
                ('number', models.CharField(max_length=24, unique=True, verbose_name='Вх. № справки')),
                ('date', models.DateField(verbose_name='Дата')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка')),
                ('storage_key', models.CharField(blank=True, max_length=1024, verbose_name='MinIO object key')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME тип')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Размер (байт)')),
                ('countries', models.ManyToManyField(related_name='documents', to='documents.country', verbose_name='Страны')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
