# Generated by Django 5.2.10 on 2026-02-19 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.ForeignKey(help_text='Управление, добывшее (предоставившее) документ', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='users.department', verbose_name='Управление'),
        ),
        migrations.AddField(
            model_name='document',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='documenttask',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tasks', to='documents.document', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='documentsubtask',
            name='document_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_subtasks', to='documents.documenttask', verbose_name='Задача'),
        ),
        migrations.AlterUniqueTogether(
            name='externaldepartment',
            unique_together={('title', 'year')},
        ),
        migrations.AddField(
            model_name='document',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.externaldepartment', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='document',
            name='realization',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, related_name='document_realization', to='documents.externaldepartment', verbose_name='Реализация'),
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('title', 'year')},
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.source', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='documentsubtask',
            name='subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.subtask', verbose_name='Подзадача'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('title', 'created_at'), name='uniq_task_title_per_day'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='documents.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='documenttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_tasks', to='documents.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='document',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='documents', through='documents.DocumentTask', to='documents.task'),
        ),
        migrations.AlterUniqueTogether(
            name='documentsubtask',
            unique_together={('document_task', 'subtask')},
        ),
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together={('task', 'title')},
        ),
        migrations.AddIndex(
            model_name='documenttask',
            index=models.Index(fields=['task'], name='documents_d_task_id_6bd10c_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttask',
            index=models.Index(fields=['document'], name='documents_d_documen_987019_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttask',
            unique_together={('document', 'task')},
        ),
    ]
