# Generated by Django 5.2.10 on 2026-01-29 08:01

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterField(
            model_name='document',
            name='subtask',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='task', chained_model_field='task', on_delete=django.db.models.deletion.PROTECT, to='documents.subtask', verbose_name='Подзадача'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('task', 'title')},
        ),
    ]
