# Generated by Django 5.2.10 on 2026-02-19 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_direction_alter_document_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания направления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
    ]
