# Generated by Django 5.2.10 on 2026-01-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options_alter_document_subtask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='MIME тип'),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='document',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Размер (байт)'),
        ),
        migrations.AddField(
            model_name='document',
            name='storage_key',
            field=models.CharField(blank=True, max_length=1024, verbose_name='MinIO object key'),
        ),
    ]
