# Generated by Django 5.2.10 on 2026-02-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_direction_created_at_direction_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(default=2026, verbose_name='Описание источника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direction',
            name='year',
            field=models.SmallIntegerField(default=2026, verbose_name='Год'),
        ),
    ]
