# Generated by Django 5.2.10 on 2026-01-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_content_type_document_original_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='link',
        ),
    ]
