# Generated by Django 5.2.10 on 2026-02-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_source_description_alter_direction_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание источника'),
        ),
    ]
