# Generated by Django 5.2.10 on 2026-01-29 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_link'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='DocumentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closes_task_fully', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tasks', to='documents.document')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_tasks', to='documents.task')),
            ],
            options={
                'unique_together': {('document', 'task')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='documents', through='documents.DocumentTask', to='documents.task'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='subtask',
        ),
        migrations.RemoveField(
            model_name='document',
            name='task',
        ),
        migrations.CreateModel(
            name='DocumentSubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.subtask')),
                ('document_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_subtasks', to='documents.documenttask')),
            ],
            options={
                'unique_together': {('document_task', 'subtask')},
            },
        ),
    ]
