# Generated by Django 5.2.10 on 2026-01-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_unique_together_documenttask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(max_length=24, unique=True, verbose_name='Вх. № справки'),
        ),
    ]
