# Generated by Django 5.2.10 on 2026-02-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_source_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaldepartment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание ведомства'),
        ),
    ]
