# Generated by Django 5.2.10 on 2026-01-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsubtask',
            options={'verbose_name': 'Подзадача (документы)', 'verbose_name_plural': 'Подзадачи (документы)'},
        ),
        migrations.AlterModelOptions(
            name='documenttask',
            options={'verbose_name': 'Задача (документы)', 'verbose_name_plural': 'Задачи (документы)'},
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AddIndex(
            model_name='documenttask',
            index=models.Index(fields=['task'], name='documents_d_task_id_6bd10c_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttask',
            index=models.Index(fields=['document'], name='documents_d_documen_987019_idx'),
        ),
    ]
