# Generated by Django 5.2.10 on 2026-01-29 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_documentsubtask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsubtask',
            name='closes_task_fully',
            field=models.BooleanField(default=False, verbose_name='Подзадача закрыта'),
        ),
        migrations.AlterField(
            model_name='documentsubtask',
            name='document_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_subtasks', to='documents.documenttask', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='documentsubtask',
            name='subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.subtask', verbose_name='Подзадача'),
        ),
        migrations.AlterField(
            model_name='documenttask',
            name='closes_task_fully',
            field=models.BooleanField(default=False, verbose_name='Подзадача закрыта'),
        ),
        migrations.AlterField(
            model_name='documenttask',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tasks', to='documents.document', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='documenttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_tasks', to='documents.task', verbose_name='Задача'),
        ),
    ]
