# Generated by Django 5.2.10 on 2026-01-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_documentsubtask_closes_task_fully_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttask',
            name='closes_task_fully',
            field=models.BooleanField(default=False, verbose_name='Задача закрыта'),
        ),
    ]
