# Generated by Django 5.2.10 on 2026-01-29 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_documenttask_closes_task_fully'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsubtask',
            name='closes_task_fully',
        ),
        migrations.AddField(
            model_name='subtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания задачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtask',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Подзадача закрыта'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания задачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Задача закрыта'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
    ]
