# Generated by Django 5.2.10 on 2026-02-26 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_document_realization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsubtask',
            name='document_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_subtasks', to='documents.documenttask', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='documenttask',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tasks', to='documents.document', verbose_name='Документ'),
        ),
    ]
