# Generated by Django 5.2.10 on 2026-03-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_documentsubtask_document_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание направления'),
        ),
    ]
