# Generated by Django 5.2.10 on 2026-01-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_task_description_task_uniq_task_title_per_day'),
        ('users', '0005_alter_department_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='users.department', verbose_name='Управление, добывшее документ'),
        ),
    ]
