# Generated by Django 5.2.10 on 2026-01-30 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_document_department'),
        ('users', '0005_alter_department_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='department',
            field=models.ForeignKey(default=3, help_text='Управление, добывшее (предоставившее) документ', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='users.department', verbose_name='Управление'),
            preserve_default=False,
        ),
    ]
