# Generated by Django 5.2.10 on 2026-02-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_alter_document_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.TextField(max_length=512, verbose_name='Подзадача'),
        ),
    ]
