# Generated by Django 5.2.10 on 2026-02-26 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0009_alter_document_executor_alter_document_realization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(blank=True, max_length=1024, verbose_name='MinIO object key')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME тип')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Размер (байт)')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('reg_number', models.CharField(max_length=50, unique=True, verbose_name='Регистрационный номер')),
                ('reg_date', models.DateField(verbose_name='Дата регистрации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок исполнения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Отметка об исполнении')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный исполнитель')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_documents', to='documents.externaldepartment', verbose_name='Откуда поступил')),
            ],
            options={
                'verbose_name': 'Входящий документ',
                'verbose_name_plural': 'Входящие документы',
                'ordering': ['-reg_date'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(blank=True, max_length=1024, verbose_name='MinIO object key')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME тип')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Размер (байт)')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('reg_number', models.CharField(max_length=50, unique=True, verbose_name='Регистрационный номер исходящего')),
                ('reg_date', models.DateField(verbose_name='Дата исполнения')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incoming', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_documents', to='correspondence.incomingdocument', verbose_name='Основание (входящий документ)')),
                ('realization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_documents', to='documents.externaldepartment', verbose_name='Куда реализован')),
            ],
            options={
                'verbose_name': 'Исходящий документ',
                'verbose_name_plural': 'Исходящие документы',
                'ordering': ['-reg_date'],
            },
        ),
    ]
