# Generated by Django 5.2.10 on 2026-02-26 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0001_initial'),
        ('documents', '0010_alter_document_realization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingdocument',
            name='incoming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_documents', to='correspondence.incomingdocument', verbose_name='Основание (входящий документ)'),
        ),
        migrations.AlterField(
            model_name='outgoingdocument',
            name='realization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realized_outgoing_documents', to='documents.externaldepartment', verbose_name='Куда реализован'),
        ),
    ]
