# Generated by Django 5.2.10 on 2026-02-26 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0002_alter_outgoingdocument_incoming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingdocument',
            name='incoming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_documents', to='correspondence.incomingdocument', verbose_name='Основание (входящий документ)'),
        ),
    ]
