# Generated by Django 5.2.10 on 2026-02-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRef',
            fields=[
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.country',),
        ),
        migrations.CreateModel(
            name='ExternalDepartmentRef',
            fields=[
            ],
            options={
                'verbose_name': 'Ведомство',
                'verbose_name_plural': 'Ведомства',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.externaldepartment',),
        ),
        migrations.CreateModel(
            name='SourceRef',
            fields=[
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.source',),
        ),
        migrations.CreateModel(
            name='SubtaskRef',
            fields=[
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.subtask',),
        ),
        migrations.CreateModel(
            name='TaskRef',
            fields=[
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.task',),
        ),
    ]
