# Generated by Django 5.2.10 on 2026-02-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0016_alter_subtask_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionRef',
            fields=[
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.direction',),
        ),
        migrations.CreateModel(
            name='SourceRef',
            fields=[
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.source',),
        ),
        migrations.CreateModel(
            name='SubtaskRef',
            fields=[
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.subtask',),
        ),
        migrations.CreateModel(
            name='TaskRef',
            fields=[
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.task',),
        ),
    ]
