# Generated by Django 5.2.10 on 2026-02-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_direction_created_at_direction_updated_at'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionRef',
            fields=[
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documents.direction',),
        ),
    ]
